제어문 : 조건식 : if, if ~ else, if ~ elif ~ else
         반복문 : while, for
함수

In [1]:
print("나무를 1번 찍었습니다.")
print("나무를 2번 찍었습니다.")
print("나무를 3번 찍었습니다.")
print("나무를 4번 찍었습니다.")
print("나무를 5번 찍었습니다.")
print("나무를 6번 찍었습니다.")
print("나무를 7번 찍었습니다.")
print("나무를 8번 찍었습니다.")
print("나무를 9번 찍었습니다.")
print("나무를 10번 찍었습니다.")
print("나무가 넘어갑니다.")

나무를 1번 찍었습니다.
나무를 2번 찍었습니다.
나무를 3번 찍었습니다.
나무를 4번 찍었습니다.
나무를 5번 찍었습니다.
나무를 6번 찍었습니다.
나무를 7번 찍었습니다.
나무를 8번 찍었습니다.
나무를 9번 찍었습니다.
나무를 10번 찍었습니다.
나무가 넘어갑니다.


In [7]:
a = 10
b = a;
print(b)
i = 1 
while i <= 10: # 1
    # print(f"나무를 {i}번 찍었습니다.") # 2
    # print("나무를 {0}번 찍었습니다.".format(i))
    print("나무를 {num}번 찍었습니다.".format(num = i))
    # print("나무를 %d번 찍었습니다." % i)
    # 3
    i = i + 1# i = 1 + 1 , i = 2 + 1, 1 = 10 + 1
    # 1 - 2 - 3 - 1 - 2- 3 - ...- 1
print("나무가 넘어갑니다.")

10
나무를 1번 찍었습니다.
나무를 2번 찍었습니다.
나무를 3번 찍었습니다.
나무를 4번 찍었습니다.
나무를 5번 찍었습니다.
나무를 6번 찍었습니다.
나무를 7번 찍었습니다.
나무를 8번 찍었습니다.
나무를 9번 찍었습니다.
나무를 10번 찍었습니다.
나무가 넘어갑니다.


In [9]:
# 8단 출력
print(f"8  * 1 = {8*1}")
print(f"8  * 2 = {8*2}")
print(f"8  * 3 = {8*3}")
print(f"8  * 4 = {8*4}")
print(f"8  * 5 = {8*5}")
print(f"8  * 6 = {8*6}")
print(f"8  * 7 = {8*7}")
print(f"8  * 8 = {8*8}")
print(f"8  * 9 = {8*9}")

print("=" * 30)

i = 1
while i <= 9:
    print(f"8  * {i} = {8*i}")
    #i = i + 1
    i += 1

8  * 1 = 8
8  * 2 = 16
8  * 3 = 24
8  * 4 = 32
8  * 5 = 40
8  * 6 = 48
8  * 7 = 56
8  * 8 = 64
8  * 9 = 72
8  * 1 = 8
8  * 2 = 16
8  * 3 = 24
8  * 4 = 32
8  * 5 = 40
8  * 6 = 48
8  * 7 = 56
8  * 8 = 64
8  * 9 = 72


In [11]:
dan = int(input("단을 입력하여 주세요. ")) # 5
i = 1
while i <= 9:
    print(f"dan  * {i} = {dan*i}")
    i += 1

단을 입력하여 주세요. 5
dan  * 1 = 5
dan  * 2 = 10
dan  * 3 = 15
dan  * 4 = 20
dan  * 5 = 25
dan  * 6 = 30
dan  * 7 = 35
dan  * 8 = 40
dan  * 9 = 45


In [13]:
# 5단 출력
i = 1
while i <= 9:
    print(f"5  * {i} = {5*i}")
    i += 1
# 6단 출력
i = 1
while i <= 9:
    print(f"6  * {i} = {6*i}")
    i += 1
# 7단 출력
i = 1
while i <= 9:
    print(f"7  * {i} = {7*i}")
    i += 1

5  * 1 = 5
5  * 2 = 10
5  * 3 = 15
5  * 4 = 20
5  * 5 = 25
5  * 6 = 30
5  * 7 = 35
5  * 8 = 40
5  * 9 = 45


In [15]:
# 2중 반복문
dan = 5
while dan <= 7:
    i = 1
    while i <= 9:
        print(f"{dan}  * {i} = {dan*i}")
        i += 1
    dan += 1

5  * 1 = 5
5  * 2 = 10
5  * 3 = 15
5  * 4 = 20
5  * 5 = 25
5  * 6 = 30
5  * 7 = 35
5  * 8 = 40
5  * 9 = 45
6  * 1 = 6
6  * 2 = 12
6  * 3 = 18
6  * 4 = 24
6  * 5 = 30
6  * 6 = 36
6  * 7 = 42
6  * 8 = 48
6  * 9 = 54
7  * 1 = 7
7  * 2 = 14
7  * 3 = 21
7  * 4 = 28
7  * 5 = 35
7  * 6 = 42
7  * 7 = 49
7  * 8 = 56
7  * 9 = 63


In [16]:
dan = 5
while dan <= 7:
    i = 4
    while i <= 8:
        print(f"{dan}  * {i} = {dan*i}")
        i += 1
    dan += 1

5  * 4 = 20
5  * 5 = 25
5  * 6 = 30
5  * 7 = 35
5  * 8 = 40
6  * 4 = 24
6  * 5 = 30
6  * 6 = 36
6  * 7 = 42
6  * 8 = 48
7  * 4 = 28
7  * 5 = 35
7  * 6 = 42
7  * 7 = 49
7  * 8 = 56


In [17]:
startDan = int(input("시작단을 입력하세요."))
endDan = int(input("마지막단을 입력하세요."))
startGop = int(input("시작곱을 입력하세요."))
endGop = int(input("마지막곱을 입력하세요."))
dan = startDan
while dan <= endDan:
    i = startGop
    while i <= endGop:
        print(f"{dan}  * {i} = {dan*i}")
        i += 1
    dan += 1

시작단을 입력하세요.3
마지막단을 입력하세요.5
시작곱을 입력하세요.4
마지막곱을 입력하세요.8
3  * 4 = 12
3  * 5 = 15
3  * 6 = 18
3  * 7 = 21
3  * 8 = 24
4  * 4 = 16
4  * 5 = 20
4  * 6 = 24
4  * 7 = 28
4  * 8 = 32
5  * 4 = 20
5  * 5 = 25
5  * 6 = 30
5  * 7 = 35
5  * 8 = 40


In [58]:
import random
lotto = [] #빈 리스트
i = 1
while i <= 45:
    lotto.append(i)
    i += 1
print(lotto)
# rnd = random.randint(0, 44) # index를 0 ~ 44
# print(rnd)
# print(lotto[12]) 
lottosize = len(lotto) # 45
i = 1
while i <= 6:
    lottosize -= 1
    idx = random.randint(0, lottosize)
    lottonum = lotto.pop(idx)
    print(lottonum, end = ",")
    i += 1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]
23,39,41,5,15,27,

In [63]:
icnt = int(input("구매 수량을 입력하세요"))
j = 1 
while j <= icnt:
    lotto = [] # 빈 리스트
    l = 1
    while l <= 45:
        lotto.append(l)
        l += 1
    lottosize = len(lotto) 
    i = 1
    while i <= 6:
        lottosize -= 1
        idx = random.randint(0, lottosize)
        lottonum = lotto.pop(idx)
        print(lottonum, end = ",")
        i += 1
    print()
    j += 1

구매 수량을 입력하세요5
15,9,30,40,39,3,
22,12,39,8,44,29,
24,26,23,6,25,1,
2,33,26,11,23,40,
32,21,16,25,36,38,


In [64]:
### 1 ~ 100까지의 합을 구하시오.
i = 1
sum = 0
while i <= 100:
    sum += i
    i += 1
print(sum)

5050


In [66]:
i = 1
sum = 0
while True:
    if i > 100: # 반복을 중지 시킬 수 있다. 
        break
    sum += i
    i += 1
print(sum)

5050


In [70]:
# 1 ~ 20중 짝수만 출력하시오,
i = 0
while i < 20:
    i += 1
    if i % 2 != 0:
        continue
    print(i)
    

2
4
6
8
10
12
14
16
18
20


In [72]:
# 1 ~ 100중 홀수의 합을 구하시오.
i = 0
sum = 0
while i < 100:
    i += 1
    if i % 2 == 0:
        continue
    sum += i
print(sum)    


2500


In [78]:
# 1 ~ 100중 홀수의 합을 구하시오.
i = 1
sum = 0
while i <= 100:
    if i % 2 != 0:
        sum += i
    i += 1
print(sum)

2500


In [79]:
# 1 ~ 100중 홀수의 합을 구하시오.
i = 1
sum = 0
while True:
    if i > 100:
        break
    if i % 2 != 0:
        sum += i
    i += 1
print(sum)

2500


In [81]:
# 리스트에 있는 합을 구하시오
l = [1,43,5, 56]
idx = 0
listsize = len(l)
sum = 0
while idx < listsize:
    sum += l[idx]
    idx+=1
print(sum)

#### for문으로 변경
sum = 0
for num in l: # [1,43,5, 56]
    sum += num
print(sum)

t = (1,43,5, 56)
sum = 0
for num in t:
    sum += num
print(sum)

105
105
105


In [84]:
l1 = [(1,2),(3,4),(5,6)]
for num in l1:
    print(num)

for (a, b) in l1:
    print(a , b)
    print( a + b)

(1, 2)
(3, 4)
(5, 6)
1 2
3
3 4
7
5 6
11


In [85]:
l1 = [(1,2,3),(3,4,5),(5,6,7)]
for (a,b,c) in l1:
    print( a+ b + c)

6
12
18


In [86]:
l1 = [(1,2,3),(3,4),(5,6,7)]
for (a,b) in l1:
    print( a+ b + c)

ValueError: too many values to unpack (expected 2)

In [89]:
i = 1
sum = 0
while i <= 100:
    sum += i
    i += 1
print(sum)

for num in range(1 , 1 + 100):
    sum += num
print(sum)

# 1 ~ 100중 짝수만 더하시오. for문
sum = 0
for num in range(1, 101):
    if num % 2 != 0:
        continue
    sum += num
print(sum)

5050
10100
2550


In [91]:
# a퓨플에 있는 값에 3을 더한 값을 빈 리스트에 저장하시오.
a = (1,2,3,4)
result = []
for num in a:
    result.append(num * 3)
print(result)

print("=" * 30)
result = [num * 3 for num in a]
print(result)

[3, 6, 9, 12]
[3, 6, 9, 12]


In [105]:
# a튜플에서 값이 짝수인 것만 3을 곱한 값을 리스트에 추가하시오.
a = (1,2,3,4)
result = []
for num in a:
    if num % 2 == 0:
        result.append(num * 3)
print(result)

result = [num * 3 for num in a
                  if num % 2 == 0]

[6, 12]


In [108]:
# 함수
# f(x, y) = 2x + 3y
# z = f(3, 4)

def f(x, y):
    return 2*x + 3*y

z = f(3, 4)
print(z)
z =  f(5, 8)
print(z)

18
34


In [110]:
# 3단 
# 5단
# 9단

for gop in range(1, 10):
    print(f"5 * {gop} = {5 * gop}")

def guguDan(dan):
    for gop in range(1, 10):
        print(f"{dan} * {gop} = {dan * gop}")

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45


In [113]:
guguDan(3)
guguDan(5)
guguDan(9)

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81


In [117]:
# 3단출력
def dan3():
    for gop in range(1, 10):
        print(f"3 * {gop} = {3 * gop}")
def dan8():
    for gop in range(1, 10):
        print(f"8 * {gop} = {8 * gop}")

In [118]:
dan8()
dan8()
dan8()

8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72


In [116]:
dan3()
dan3()
dan3()

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27


In [ ]:
### 함수를 만드는 4가지 형식
'''
def 함수명(parameter):
    명령어1
    명령어2
    ...
    print(parameter)
    return 결과값

함수명(argument) : 인자 , 인수 : 실제 값을 가지고 있는 것
'''

In [120]:
'''1. 일반적인 함수 : parameter도 있고 결과값이 있다.'''
def f(x): # 피 호출함수
    return 3 + x * 5  # return은 결과 값을 호출함수에게 전달

z  = f(5)   # 호출함수
print(z)

28


In [122]:
def add1(x , y):
    return x + y
z = add1(3 , 4)
print(z)

7


In [124]:
'''2. 입력값은 없지만 .결과값이 있다.'''
def add():
    x = 10
    y = 30
    return x + y

z = add()
print(z)

40


In [126]:
def add():
    x = int(input("숫자를 입력해 주세요"))
    y = int(input("숫자를 입력해 주세요"))
    return x + y

z = add()
print(z)

숫자를 입력해 주세요30
숫자를 입력해 주세요30
60


In [127]:
z = add()
print(z)

숫자를 입력해 주세요30
숫자를 입력해 주세요40
70


In [128]:
'''3.입력 값은 있으나 결과값이 없다.'''
def add2(x, y):
    result = x  + y
    print(result)

In [129]:
z  = add2(30 , 20)
print(z)

50
None


In [130]:
'''4. 입력값도 없고 결과값도 없다.'''
def add3():
    x = int(input("숫자를 입력해 주세요"))
    y = int(input("숫자를 입력해 주세요"))
    print( x + y)

In [131]:
add3()

숫자를 입력해 주세요20
숫자를 입력해 주세요30
50


In [137]:
lotto = []
for n in range(1, 1 + 45):
    lotto.append(n)
# print(lotto)
lottoSize = len(lotto)
# print(lottoSize)
j = 1
while j <= 6:
    lottoSize -= 1
    idx = random.randint(0, lottoSize) #index
    num = lotto.pop(idx)
    print(num , end=", ")
    j += 1

36, 4, 23, 32, 25, 37, 

In [138]:
def lottoFnc():
    lotto = []
    for n in range(1, 1 + 45):
        lotto.append(n)
    # print(lotto)
    lottoSize = len(lotto)
    # print(lottoSize)
    j = 1
    while j <= 6:
        lottoSize -= 1
        idx = random.randint(0, lottoSize) #index
        num = lotto.pop(idx)
        print(num , end=", ")
        j += 1

In [173]:
num = int(input("수량을 입력하세요."))
i = 1
while i <= num:
    lottoFnc()
    print()
    i += 1

수량을 입력하세요.5
14, 41, 30, 35, 2, 27, 
33, 36, 2, 13, 17, 40, 
25, 14, 41, 33, 27, 35, 
7, 2, 21, 36, 20, 1, 
7, 13, 3, 16, 14, 12, 


In [174]:
# 1~~~100, 1~~~~1000, 50~~~~1000 에 해당하는 합계 값을 구하시오.
sum = 0
for i in range(1 , 1+ 100):
    sum += i
print(sum)

5050


In [175]:
def sum1(start, end):
    sum = 0
    for i in range(start , 1+ end):
        sum += i
    print(sum)

In [179]:
sum1(1, 100)
sum1(1, 1000)
sum1(50, 1000)

5050
500500
499275


In [180]:
def sum1(start, end):
    sum = 0
    for i in range(start , 1+ end):
        sum += i
    return sum

In [185]:
z = sum1(10, 1000)
print(z)

TypeError: sum1() takes 2 positional arguments but 3 were given

In [183]:
z = sum1(end = 1000, start =1 )
print(z)

500500


In [187]:
def sum11(*para): ## argument의 갯수가 일정하지 않을 때 parameter에 *를 주면 된다.
    sum = 1
    for num  in para:
        sum += num
    print(sum)

sum11(1,2)
sum11(1,2,3)
sum11(1,2,3,4)
sum11(1,2,3,4,5,6,7,8,9,10)

4
7
11
56


In [193]:
def sum11(opt, *para):
    sum = 0
    if opt == "add":
        for num in para:
            sum += num
    elif opt == "mul":
        for num in para:
            sum *= num
    print(sum)

In [196]:
sum11("add", 1,2,3,4 )
sum11("mul", 1,2,3,4,45,5,5 )

10
0


In [197]:
a , b = (10, 20)
print(a, b)

10 20


In [198]:
### return문에 의해 전달 되는 값은 오로지 하나이다.
def add_mul(x , y):
    i = x + y
    j = x * y
    return i, j

In [201]:
z = add_mul(20, 30)
print(z)
x , y = add_mul(20,50)
print(x, y)

(50, 600)
70 1000


In [202]:
def add_mul(x , y):
    i = x + y
    j = x * y
    return i # return은 함수 종료
    return j

In [206]:
#### 매개변수에 초깃값 미리 설정하기 
def say_myself(name, old, man = True):
    print("나의 이름은 %s 입니다." % name) 
    print("나이는 %d살입니다." % old)
    if man:
        print("남자입니다.")
    else:
        print("여자입니다.")

In [207]:
say_myself('이숭무',25)
say_myself('이상범',25, False)

나의 이름은 이숭무 입니다.
나이는 25살입니다.
남자입니다.
나의 이름은 이상범 입니다.
나이는 25살입니다.
여자입니다.


In [208]:
def say_myself(name, old = 25, man):
    print("나의 이름은 %s 입니다." % name) 
    print("나이는 %d살입니다." % old)
    if man:
        print("남자입니다.")
    else:
        print("여자입니다.")
        
say_myself('이상범', False)

SyntaxError: non-default argument follows default argument (3525767680.py, line 1)

In [211]:
def say_myself(name, old = 25, man = True):
    print("나의 이름은 %s 입니다." % name) 
    print("나이는 %d살입니다." % old)
    if man:
        print("남자입니다.")
    else:
        print("여자입니다.")
say_myself("노사연")
say_myself('이상범', False)
say_myself('이상범', man = False)

나의 이름은 노사연 입니다.
나이는 25살입니다.
남자입니다.
나의 이름은 이상범 입니다.
나이는 25살입니다.
여자입니다.


파이썬의 기본 자료형 : 숫자, 문지열, 리스트, 튜플, 딕셔너리, 집합, 부울<br />
제어문 : if , if ~ else, if ~ elif ~ else , 조건문<br />
         while , for , break, continue : 번복문<br />
함수

In [215]:
# numpy (numerical python)
import numpy
num = numpy.random.randint(10, size = 6)
print(num)

[2 2 5 1 9 8]


In [217]:
import numpy as np
num = np.random.randint(10, size = 6)
print(num)

[6 9 3 6 1 6]


In [221]:
print(num) # 1차원 배열
l = [6, 9, 3, 6, 1, 6]
print(l)
# index
print(num[1])
print(l[1])

[6 9 3 6 1 6]
[6, 9, 3, 6, 1, 6]
9
9


In [224]:
num2 = np.random.randint(10, size=(3, 4))  # 3 행 4열인 2차원 배열
print(num2)
l2 = [[6, 9, 9, 0] ,[8, 9 ,1 ,1],[7, 8, 9, 7]]
print(l2)

[[7 7 4 5]
 [5 4 8 6]
 [2 7 1 8]]
[[6, 9, 9, 0], [8, 9, 1, 1], [7, 8, 9, 7]]


In [225]:
num3 = np.random.randint(10, size=(1, 4))
print(num) # 1차원 배열
print(num3) # 2차원 배열

[6 9 3 6 1 6]
[[9 2 9 9]]


In [228]:
### 1차원배열과 리스트 비교
print(num) # [6 9 3 6 1 6] 
#             0 1 2 3 4 5
#             6 5 4 3 2 1 -
print(l) # [6, 9, 3, 6, 1, 6]
#           0  1  2  3  4  5
#           6  5  4  3  2  1  -
print(num[2])
print(l[2])
print(num[-4])
print(l[-4])

[6 9 3 6 1 6]
[6, 9, 3, 6, 1, 6]
3
3
3
3


In [232]:
#slicing
print(num[0:4])
print(l[0:4])
print(num[:4])
print(l[:4])
print(num[4:len(num)])
print(l[4:len(l)])
print(num[4: ])
print(l[4:])

[6 9 3 6]
[6, 9, 3, 6]
[6 9 3 6]
[6, 9, 3, 6]
[1 6]
[1, 6]
[1 6]
[1, 6]


In [239]:
print(num)
print(l)
print(num[::2])
print(l[::2])
print(num[::3])
print(l[::3])
print(num[2:6:2])
print(l[2:6:2])
print(num[::-1])
print(l[::-1])
print(num[::-2])
print(l[::-2])

[6 9 3 6 1 6]
[6, 9, 3, 6, 1, 6]
[6 3 1]
[6, 3, 1]
[6 6]
[6, 6]
[3 1]
[3, 1]
[6 1 6 3 9 6]
[6, 1, 6, 3, 9, 6]
[6 6 9]
[6, 6, 9]


In [241]:
### 배열이나 리스트에 있는 값을 변경하는 방법도 같다.
print(l)
print(num)
l[1] = 10
num[1] = 10
print(l)
print(num)

[6, 9, 3, 6, 1, 6]
[6 9 3 6 1 6]
[6, 10, 3, 6, 1, 6]
[ 6 10  3  6  1  6]


In [243]:
num2 = np.random.randint(10, size=(3, 4))
print(num2)

[[3 5 1 8]
 [1 8 4 1]
 [4 7 7 5]]


In [245]:
l2 = [[3, 5, 1, 8],[1, 8, 4, 1],[4, 7, 7, 5]]

In [252]:
print(num2)
#   4 3 2 1 -
#   0 1 2 3
# [[3 5 1 8]    # 0    3
#  [1 8 4 1]    # 1    2
#  [4 7 7 5]]   # 2    1 -
print(l2)
# [[3, 5, 1, 8], [1, 8, 4, 1], [4, 7, 7, 5]]
#       0              1             2
#       3              2             1   -
#   0  1  2  3    0  1  2  3    0  1  2  3
print(num2[1][1])
print(l2[1][1])
print(num2[1 , 1]) # num2[행, 열]
# print(l2[1 , 1])
print(num2[-2][-3]) # list style
print(l2[-2][-3])   
print(num2[-2 ,-3]) # array style

[[3 5 1 8]
 [1 8 4 1]
 [4 7 7 5]]
[[3, 5, 1, 8], [1, 8, 4, 1], [4, 7, 7, 5]]
8
8
8
8
8
8


In [268]:
# slicing
#   4 3 2 1 -
#   0 1 2 3
# [[3 5 1 8]    # 0    3
#  [1 8 4 1]    # 1    2
#  [4 7 7 5]]   # 2    1 -

# [[3, 5, 1, 8], [1, 8, 4, 1], [4, 7, 7, 5]]
#       0              1             2
#       3              2             1   -
#   0  1  2  3    0  1  2  3    0  1  2  3
print(l[0:2])
print(num2[0:2])
print(l2[1][0:2])
print(num2[1][0:2])
print(num2[1, 0:2])
print(num2[0:2 , 0:2 ])
print(l2[0:2][0:2])
print(num2[::2 , ::2])

[[3, 5, 1, 8], [1, 8, 4, 1]]
[[3 5 1 8]
 [1 8 4 1]]
[1, 8]
[1 8]
[1 8]
[[3 5]
 [1 8]]
[[3, 5, 1, 8], [1, 8, 4, 1]]
[[3 1]
 [4 7]]


In [271]:
### 열을 한칸씩 건너 띄우기
print(num2[: , ::2])
### 행을 한칸씩 건너 띄우기
print(num2[::2, :])

[[3 1]
 [1 4]
 [4 7]]
[[3 5 1 8]
 [4 7 7 5]]


In [272]:
# 두개의 행, 세개의 열
print(num2[0:2, 0:3])

[[3 5 1]
 [1 8 4]]


In [278]:
#   4 3 2 1 -
#   0 1 2 3
# [[3 5 1 8]    # 0    3
#  [1 8 4 1]    # 1    2
#  [4 7 7 5]]   # 2    1 -
print(num2[::-1])
print(num2[: , :: -1])
print(num2[::-1 , :: -1])
### 첫번째 행만 출력
print(num2[0])
print(num2[0 , :])
print(num2[:, 0])
# 1행 1열의 값을 99로 변경하시오.
num2[0][0] = 99
print(num2)

[[4 7 7 5]
 [1 8 4 1]
 [3 5 1 8]]
[[8 1 5 3]
 [1 4 8 1]
 [5 7 7 4]]
[[5 7 7 4]
 [1 4 8 1]
 [8 1 5 3]]
[3 5 1 8]
[3 5 1 8]
[3 1 4]
[[99  5  1  8]
 [ 1  8  4  1]
 [ 4  7  7  5]]


In [286]:
### 배열을 만드는 다른 방법
#  0~8까지 9개의 수를 가지는 2차원 배열
arr = np.arange(9).reshape(3,3)
print(arr)
arr1 = np.arange(12).reshape(3,4)
print(arr1)
arr2 = np.arange(12).reshape(4,3)
print(arr2)
arr3 = np.arange(12, 12+12).reshape(4,3)
print(arr3)
arr4 = np.arange(4).reshape(1, 4)
print(arr4)

# 1~3까지의 수를 가지는 1차원배열
arr5 = np.arange(1, 1+3).reshape(3)
print(arr5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[0 1 2 3]]
[1 2 3]
